wandb_version: 1

goal:
  desc: null
  value: test
device:
  desc: null
  value: cuda
device_id:
  desc: null
  value: '0'
dataset:
  desc: null
  value: Cifar10
num_classes:
  desc: null
  value: 10
model_str:
  desc: null
  value: cnn
model:
  desc: null
  value: "FedAvgCNN(\n  (conv1): Sequential(\n    (0): Conv2d(3, 32, kernel_size=(5,\
    \ 5), stride=(1, 1))\n    (1): ReLU(inplace=True)\n    (2): MaxPool2d(kernel_size=(2,\
    \ 2), stride=(2, 2), padding=0, dilation=1, ceil_mode=False)\n  )\n  (conv2):\
    \ Sequential(\n    (0): Conv2d(32, 64, kernel_size=(5, 5), stride=(1, 1))\n  \
    \  (1): ReLU(inplace=True)\n    (2): MaxPool2d(kernel_size=(2, 2), stride=(2,\
    \ 2), padding=0, dilation=1, ceil_mode=False)\n  )\n  (fc1): Sequential(\n   \
    \ (0): Linear(in_features=1600, out_features=512, bias=True)\n    (1): ReLU(inplace=True)\n\
    \  )\n  (fc): Linear(in_features=512, out_features=10, bias=True)\n)"
batch_size:
  desc: null
  value: 10
local_learning_rate:
  desc: null
  value: 0.005
learning_rate_decay:
  desc: null
  value: false
learning_rate_decay_gamma:
  desc: null
  value: 0.99
global_rounds:
  desc: null
  value: 200
local_epochs:
  desc: null
  value: 5
algorithm:
  desc: null
  value: FedTest
join_ratio:
  desc: null
  value: 1.0
random_join_ratio:
  desc: null
  value: false
num_clients:
  desc: null
  value: 100
prev:
  desc: null
  value: 0
times:
  desc: null
  value: 1
eval_gap:
  desc: null
  value: 1
privacy:
  desc: null
  value: false
dp_sigma:
  desc: null
  value: 0.0
save_folder_name:
  desc: null
  value: items
auto_break:
  desc: null
  value: false
dlg_eval:
  desc: null
  value: false
dlg_gap:
  desc: null
  value: 100
batch_num_per_client:
  desc: null
  value: 2
num_new_clients:
  desc: null
  value: 0
fine_tuning_epoch:
  desc: null
  value: 0
log:
  desc: null
  value: true
noniid:
  desc: null
  value: false
balance:
  desc: null
  value: false
alpha_dirich:
  desc: null
  value: 0.1
client_drop_rate:
  desc: null
  value: 0.0
train_slow_rate:
  desc: null
  value: 0.0
send_slow_rate:
  desc: null
  value: 0.0
time_select:
  desc: null
  value: false
time_threthold:
  desc: null
  value: 10000
beta:
  desc: null
  value: 0.0
lamda:
  desc: null
  value: 1.0
mu:
  desc: null
  value: 0
K:
  desc: null
  value: 5
p_learning_rate:
  desc: null
  value: 0.01
M:
  desc: null
  value: 5
itk:
  desc: null
  value: 4000
alphaK:
  desc: null
  value: 1.0
sigma:
  desc: null
  value: 1.0
alpha:
  desc: null
  value: 1.0
plocal_steps:
  desc: null
  value: 1
tau:
  desc: null
  value: 1.0
fine_tuning_steps:
  desc: null
  value: 10
dr_learning_rate:
  desc: null
  value: 0.0
L:
  desc: null
  value: 1.0
noise_dim:
  desc: null
  value: 512
generator_learning_rate:
  desc: null
  value: 0.005
hidden_dim:
  desc: null
  value: 512
server_epochs:
  desc: null
  value: 1000
localize_feature_extractor:
  desc: null
  value: false
server_learning_rate:
  desc: null
  value: 1.0
eta:
  desc: null
  value: 1.0
rand_percent:
  desc: null
  value: 80
layer_idx:
  desc: null
  value: 2
mentee_learning_rate:
  desc: null
  value: 0.005
T_start:
  desc: null
  value: 0.95
T_end:
  desc: null
  value: 0.98
lamda_reg:
  desc: null
  value: 0.0
cagrad_rounds:
  desc: null
  value: 100
cagrad_learning_rate:
  desc: null
  value: 25.0
momentum:
  desc: null
  value: 0.5
step_size:
  desc: null
  value: 30
gamma:
  desc: null
  value: 0.9
run_name:
  desc: null
  value: FedTest__Cifar10__100__1704637296
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1704637298.5146
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 2
      - 3
      - 5
      - 41
      - 53
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.11.5
      5: 0.16.0
      8:
      - 5
      13: linux-x86_64
